# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://129.28.177.97:3306/panda?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/panda?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&&serverTimezone=Asia/Shanghai

    username: root
    password: 123456789

logging:
  level:
     com.graduation.panda.dao : debug






